### ISSUE TITLE
Lab tests have a misspelling too

### ISSUE THREAD

**Issue by amyjoscelyn** [learn-co-curriculum/wwdc-badges-methods#18]
@markedwardmurray 

I edited the "greeetings" so it only has two Es in the lab instructions.  But in the lab the same misspelling is there; not only that, but my build wouldn't succeed until I included the misspelling in my method name too, because that's what the tests were expecting to see.

**Comment by markedwardmurray** [comment]
changed the misspelling in the test file and in the readme when declaring the method
