### ISSUE TITLE
Reading mentions 'refresher' on objects when objects haven't been introduced yet

### ISSUE THREAD

**Issue by JessRudder** [learn-co-curriculum/wwdc-badges-methods#3]
The reading currently says:

To refresh on the difference between a class / instance method, check our reading: Intro To Objects.

On Learn, class/instance methods (and objects) haven't been introduced yet.  That happens in the next section (4-5 lessons away).

Objects should either be introduced sooner or this should be rewritten with a brief overview of objects and a note that we'll learn more later.

**Comment by markedwardmurray** [comment]
This has been removed in the rewrite. Thanks for pointing it out!

**Comment by JessRudder** [comment]
@markedwardmurray - you guys are the best!
