### ISSUE TITLE
need more reference points

### ISSUE THREAD

**Issue by SophieDeBenedetto** [learn-co-curriculum/wwdc-badges-methods#6]
This lab was hard for me to complete without doing outside googling. First time we are doing all of these things on our own: 

* iterating
* building methods
* string interpolation
* building arrays

I think this will in part be solved by adding mini-labs after previous readmes as discussed but all could use some reminders and hints throughout the readme. Just thinking of someone alone at home trying to do this and that person needs more hand holding than we are used to providing. 

@markedwardmurray

**Comment by markedwardmurray** [comment]
were the directions unclear, or was it that you had difficulty remembering how to accomplish things from the onslaught of readings?

**Comment by SophieDeBenedetto** [comment]
directions were clear. I didn't remember how to accomplish things b/c I had never tried it before and didn't remember which readings discussed which thing and ended up being easier to google than go back.

**Comment by markedwardmurray** [comment]
some of this should be addressed by adding the code-along labs objc-parrot and objc-speaking-grandma

**Comment by AnnJohn** [comment]
Closing issue
